### PR TITLE
added delete

### PR DESCRIPTION
**Pull request by Bhupesh-V**
and please shift the code to pure CPP
(avoid free) and printf functions

### CODE REVIEW

**Comment by Bhupesh-V** [comment]
and there is a issue i think with the search function
(its not working properly after delete ;) sry)

**Comment by Animesh-Ghosh** [comment]
Another guy has requested some changes in another pull request. Use his Search function for the Tree along with your Delete function. If it still doesn't work then we'll raise a public gist for your Delete function.

**Comment by Animesh-Ghosh** [comment]
Update your fork. Create a new function with C++ dynamic memory allocation operators.

**Comment by Pranav-Khurana** [comment]
Probably there are errors in traversal too, i tried to run the code on my PC but the nodes were not inserted (except the first element) and both the traversals were showing only one element. Either there's error in traversal or in insertion.

**Comment by Animesh-Ghosh** [comment]
Is the current version running, @Pranav-Khurana ? If so, we cant start making changes from there, one by one. @Bhupesh-V update your fork man. Discard malloc() and free().

**Pull request closed without merging**
