### PR TITLE
added clearscreen.md

### PR DESCRIPTION
**Pull request by Bhupesh-V**
Coming from issue #7
The readme requires more amount of work to be done

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
@Gobtotem review kar. Anything more to add?

**Comment by Animesh-Ghosh** [comment]
@Bhupesh-V @Gobtotem add information for Windows systems as well.

**Comment by Bhupesh-V** [comment]
I guess this you should do
I am not on windows 😁

**Comment by ghost** [comment]
For windows :-
`gcc test.c clearscreen.c -o test`

**Comment by Animesh-Ghosh** [comment]
@Bhupesh-V @Gobtotem check the README.md now. If it's looking OK to you both I will commit it. Thanks for all the help!

**Comment by ghost** [comment]
Looks okay to me. :+1:

**Comment by Bhupesh-V** [comment]
Yeah it's fine :+1:

**Pull request merged**
